# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6ee6b866355ec966951fafd8102125bc109a6771889802e422d780db99e57a552ae5052b84b1c91416b2c59b522be36940200aad6475995b02c5094aaf0b089

test:
  secret_key_base: c43f5cb3978bc5607d836f53a5bbf5d23e59e81080e436a2c043a9308a3a3807e3bdab5261aab8c1c1145e395373db1f8aad86822f397b027b87d3edaa34f4c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
